- .github/workflows/medcat-v2_release.yml
- medcat-v2/.release/prepare_minor_release.sh
- medcat-v2/.release/prepare_patch_release.sh
This would hopefully make it so that releases for MedCAT v2 make sense.
The changes
- Release branch is now `medcat/v<major>.<minor>`
- Before just `release/v<major>.<minor>`
- Release tag now `medcat/v<major>.<minor>.<patch>`
- Before just `v<major>.<minor>.<parch>`
- Makes changes to both the release scripts as well as the actual workflow
> CU-8699j8f1r Update release workflow for MedCAT v2

- .github/workflows/medcat-v2_release.yml
- medcat-v2/.release/README.md
Just documentation fixes.
Changes:
1. Fix branch name in comment in release workflow
2. Update `medcat-v2/.release` folder README to include correct branch name
3. Update `medcat-v2/.release` folder README to incldue tag format
> Small release documention fixes

- medcat-v2-tutorials/notebooks/introductory/relcat/2._Infering_relations_from_annotations_with_Relation_toolkit.ipynb
- medcat-v2/medcat/cat.py
- medcat-v2/medcat/cdb/cdb.py
- medcat-v2/medcat/utils/defaults.py
- medcat-v2/medcat/vocab.py
- medcat-v2/tests/cdb/test_cdb.py
- medcat-v2/tests/test_cat.py
- medcat-v2/tests/test_vocab.py
This PR allows `CDB.load` and the `Vocab.load` methods to convert legacy models on the fly.
It also adds a few small tests.
The PR still allows the user to disable this feature by setting `MEDCAT_AVOID_LECACY_CONVERSION` to `True`.
> CU-8699may9k Allow CDB and Vocab load to convert from legacy

- medcat-v2/medcat/components/ner/trf/deid.py
This PR adds a multirpocessing method to DeID models.
> CU-8699pv8uw: Add multiprocessing method to DeID

- medcat-v2/medcat/cat.py
- medcat-v2/tests/test_cat.py
Turns out the current multiprocessing pipeline had a few issues.
It would work fine if number of process wasn't specified (since it would do them in sequence).
However, if the number of processes specified was 2 (or greater) processing an empty list of texts would fail. This was becaue the assumption of the method was that work would be distributed accross all workers, and subsequently there's a future for every worked. But in case of an empty input there were no futures.
Furthermore, if the number of processes was 3 (or greater), passing a small list of input texts also often resulted in an exception being raised. This is because with 2 processes, only 1 external worker is spawned, and it gets some texts to manage, and subsequently leaves nothing for the main process (which is fine). But …
> Cu 8699qbr8e Multiprocessing empty batches

- medcat-v2/medcat/cat.py
This should fix the issue I've been having in `medcat-service` regarding multiprocessing just hanging.
Apprently there's a difference how MacOS (locally) works with separate processes and how Linux (on GHA workflow) does it. So this PR should fix that. I've checked that (to an extent) on the `medcat-service` related PR.
With that said, I'm not 100% sure why regular GHA workflow didn't catch this as there is some multiprocessing in there that's being tested.
> CU-8699qg2tg: Force spawn-based multirpocessing

- .github/workflows/medcat-v2_release.yml
The PyPI install action would otherwise try to include all the `.tar.gz` files. And while checking some of the, it realises it has unexpected stuff in it, and fails.
> Remove install bundles before pushing to PyPI

- medcat-v2/README.md
- medcat-v2/docs/main.md
The docs link was pointing at the old page that built based on the old repo.
Now pointing to the new one.
> CU-8699twteb: Update docs links to point to up to date page

- medcat-demo-app/webapp/requirements.txt
- medcat-service/Dockerfile
- medcat-service/requirements.txt
- medcat-v2-tutorials/notebooks/introductory/meta/1._Add_a_MetaCat_to_a_Model.ipynb
- medcat-v2-tutorials/notebooks/introductory/migration/1._Migrate_v1_model_to_v2.ipynb
- medcat-v2-tutorials/notebooks/introductory/relcat/1._Supervised_Training_Relation_Extraction.ipynb
- medcat-v2-tutorials/requirements.txt
- medcat-v2/README.md
- medcat-v2/docs/main.md
Now that there's a PyPI (beta) release of medcat v2, we can install based on that.
This involvest stuff that has a direct dependence on medcat (v2).
Due to not depending on installation based on GitHub repositories, the `medcat-service` image does not need `git` to build.
> CU-8699rvhe9 Refer to PyPI medcat v2

- medcat-v2/medcat/cat.py
- medcat-v2/medcat/components/addons/meta_cat/meta_cat.py
- medcat-v2/medcat/pipeline/pipeline.py
- medcat-v2/tests/test_cat.py
This PR adds the following functionatlity:
- Allows a `config_dict` to be passed to `CAT.load_model_pack` to merge a config before the pipe is initialised
- Allows a `addon_config_dict` to be passed to `CAT.load_model_pack` to merge in addon-specific config(s) before addon initialisation
- This expects the name (e.g `meta_cat.Subject`) to be mapped to the config for that addon
- Allows `addon_config_dict` to be passed to `CAT.load_addons` to merge addon-specific config(s) before their initialisation
- Similarly to the above
- Adds a few tests regarding the above
> CU-8699vkmu4: Allow load with merging config(s)

- .github/workflows/medcat-service_docker.yml
https://github.com/CogStack/cogstack-nlp/actions/runs/16372680383/job/46264753505
This build triggered on a release of medcat, and updated the latest tag in docker making it go back in time vs main
Two fixes here:
- Stop it building on a release, I think a tag is enough
- Stop it setting :latest tag when built on a tag (the flavour setting)
> build(medcat-service): Fix latest tag in docker getting set on a release

- .github/workflows/medcat-trainer_qa.yml
- .github/workflows/medcat-trainer_release.yml
- .github/workflows/medcat-v1_main.yml
- .github/workflows/medcat-v1_production.yml
https://github.com/CogStack/cogstack-nlp/actions/runs/16799617477/job/47577705902
```
Warning: Unexpected input(s) 'packages-dir', valid inputs are ['entryPoint', 'args', 'user', 'password', 'repository_url', 'packages_dir', 'verify_metadata', 'skip_existing', 'verbose']
Run pypa/gh-action-pypi-publish@v1.4.2
with:
repository_url: https://test.pypi.org/legacy/
packages-dir: medcat-trainer/dist
user: __token__
packages_dir: dist
verify_metadata: true
skip_existing: false
verbose: false
env:
pythonLocation: /opt/hostedtoolcache/Python/3.10.18/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.18/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64 …
```
> build(medcat-trainer): Fix pypi publish CU-869a1x4fh

- medcat-v2/README.md
- medcat-v2/docs/migration_guide_v2.md
This PR attempt to add a migration guide for v2.
The document is linked in the medcat-v2 README.
It attempt to explain most of the grievences when moving from v1 to v2 as well as provide some FAQ for users.
> CU-8698x63kt: Add v2 migration guide

- README.md
- anoncat-demo-app/README.md
- anoncat-demo-app/app/frontend/src/App.vue
- medcat-trainer/README.md
- medcat-trainer/docs/installation.md
- medcat-trainer/docs/maintenance.md
- medcat-trainer/docs/project_admin.md
- medcat-trainer/install.sh
- medcat-trainer/notebook_docs/API_Examples.ipynb
- medcat-trainer/notebook_docs/Generate_CUI_Filters.ipynb
- medcat-trainer/notebook_docs/Processing_Annotations.ipynb
- medcat-trainer/webapp/scripts/load_examples.py
- medcat-v1/docs/main.md
- medcat-v2-tutorials/README.md
- medcat-v2-tutorials/notebooks/introductory/basic/3._Supervised_training_on_model.ipynb
- medcat-v2/README.md
- medcat-v2/docs/main.md
- medcat-v2/pyproject.toml
still TODO - Update medcat-v1 and medcat-v1-tutorials
> CU-8699mrvup docs: update urls throughout to point to new cogstack-nlp repo

- .github/workflows/medcat-v2_release.yml
Otherwise it would also run on v1 release, but fail.
E.g:
https://github.com/CogStack/cogstack-nlp/actions/runs/16905576431/job/47894459863
> Avoid v2 release workflow run in case of v1 release

- .github/dependabot.yml
- .github/workflows/medcat-service_docker.yml
- Dont run docker push if user is dependnadabot
- Group dependency updates into one PR
> build: Update dependabot config

- medcat-service/medcat_service/nlp_processor/medcat_processor.py
- medcat-service/medcat_service/test/test_deid.py
Used the solution from https://github.com/CogStack/cogstack-nlp/blob/e55bf6cd3fd453c0feafb10f50d33d5732c7ace0/medcat-demo-app/webapp/demo/views.py
I didnt work out why it was returning np.float for DeID mode but not for the regular mode (noting regular just returns 1 in the tests, so could be that). I also didnt work out a better way to make pydantic convert them automatically, seemed like a lot. 
```
INFO:API:Process_result is text='[**********] says hello' annotations=[{0: {'pretty_name': 'PATIENT', 'cui': 'PATIENT', 'type_ids': [], 'source_value': 'John smith', 'detected_name': '', 'acc': np.float32(0.77323574), 'context_similarity': np.float32(0.77323574), 'start': 0, 'end': 10, 'id': 0, 'meta_anns': {}, 'context_left': [], 'context_center': [], 'context_right': []}}] success=True …
```
> bug(medcat-service): Fix DeID mode fails with PydanticSerializationError

- .github/workflows/medcat-trainer_qa.yml
Attempting to fix the trainer QA workflow.
I _think_ this was just an issue of it trying to push the same version (1.0.0) over and over again. And that was just failing because the test PyPI rejected the duplicate.
EDIT:
Also made the workflow run at PR time so I can check without a merge.
> CU-869a4wpek Trainer qa workflow fix

- .github/workflows/medcat-trainer-v1_qa.yml
This was an oversight in #103 where it still needed the job that was removed. And because of that the workflow would fail to run (e.g https://github.com/CogStack/cogstack-nlp/actions/runs/17099268212).
> Fix trainer v1 QA workflow

- medcat-v2-tutorials/README.md
Looks like the links weren't correct in the README.
> CU-869a6v8qd: Fix tutorial links

- medcat-v2/README.md
> chore(medcat): CU-869a971xa: Update readme 

- .gitignore
- medcat-trainer/docker-compose-prod.yml
- medcat-trainer/docker-compose.yml
- v1/medcat-trainer/docker-compose-prod.yml
- v1/medcat-trainer/docker-compose.yml
latest release up on dev, was release tagged a while ago...
> chore(medcattrainer): update to latest release

- medcat-v2/medcat/cat.py
- medcat-v2/medcat/config/__init__.py
- medcat-v2/medcat/model_creation/cdb_maker.py
- medcat-v2/medcat/pipeline/__init__.py
- medcat-v2/medcat/stats/__init__.py
- medcat-v2/medcat/trainer.py
Improving some imports like `from medcat.pipeline.pipeline import Pipeline` and `from medcat.stats.stats import get_stats`.
And a few more slight simplfications (e.g with `medcat.config` package).
> CU-869a9mten Improve duplicate name imports

- medcat-v2/medcat/utils/legacy/conversion_all.py
This fixes 2 small issues with converted model names:
- If it's a `.zip`, the previous implementation would leave teh `.zip` in the middle of the new name
- That's because the save mechanism adds the hash and extension (unless otherwise specified)
- If it's a folder, the converter would fail
- Because the `old_model_name` attribute wasn't set
EDIT: This is an extension of #118
> Medcat conversion model name hotfix

- .github/workflows/medcat-trainer_ci.yml
- .github/workflows/medcat-trainer_qa.yml
- medcat-trainer/webapp/frontend/package-lock.json
- medcat-trainer/webapp/frontend/package.json
- medcat-trainer/webapp/frontend/src/tests/App.spec.ts
- medcat-trainer/webapp/frontend/src/tests/views/ConceptDatabase.spec.ts
- medcat-trainer/webapp/frontend/src/tests/views/Demo.spec.ts
- medcat-trainer/webapp/frontend/src/tests/views/Home.spec.ts
- medcat-trainer/webapp/frontend/src/tests/views/MetricsHome.spec.ts
- Add c8 & Instanbul for test coverage report
- Add jobs in CI and QA workflows
> CU-869admfwg: Add basic tests in MedCAT Trainer

- medcat-v2/medcat/cat.py
- medcat-v2/tests/test_cat.py
- medcat-v2/tests/utils/ner/test_deid.py
When  is provided, the user (probably) expects the data to be saved on disk upon method call. But the current implementation forced the user to iterate over the results to force the annotation to actually happen.
~~So this change allows the method to materialise the list internally to force the annotation to happen and results to be saved on disk. Additionally, it adds 2 other options:~~
1. ~~The lazy iteration (what happens when no  is provided) where the iteration of data is left to the user~~
2. ~~The combined / saved and return option where the results are materialised, but also yielded. Notably, this will take up a lot of memory if/when used with large data sets~~
Instead of the above, the current version of the PR introduces a new method:
`CAT.save_entities_multi_texts` that:
a) …
> CU-869ahw0mw: Add argument to control data flow when saving results.

- medcat-v2/medcat/cat.py
- medcat-v2/medcat/config/config.py
- medcat-v2/tests/test_cat.py
This PR adds back the functionality from v1 that added mappings to other ontologies to the output of `get_entities`.
This PR adds this back, but with a slightly differtent approach. I've opted to make this a config option that can be changed if / when needed, instead of an extra argument to the method(s).
> feat(medcat): CU-869aknekf Add mapping to ontologies

- medcat-v2/medcat/components/linking/context_based_linker.py
- medcat-v2/medcat/utils/postprocessing.py
- medcat-v2/tests/utils/test_postprocessing.py
**The issue**
whether the config.general.show_nested_entities flag is True or False, there seems to be no effect to the output.
**Example**
if the text is “chest pain” which matches 1) “chest pain” greedily 2) “chest” 3) “pain”, it seems to produce all 3 entities at the end at all time regardless of the flag.
**What's wrong**
- the current logic in postprocessing.py doesn't seem to be filtering anything.
- the filtering logic doesn't appear to look at the flag at all.
**The fix**
- re-implementation of the filtering logic to simply use token index to filter.
- the flag is passed on and checked during post-processing.
> fix for config.general.show_nested_entities
